import { asc, eq, sql } from "drizzle-orm";
import { getDb } from "@/db";
import { bookmarks, progress, studyDecks, words } from "@/db/schema";
import { getChatGPTUser } from "@/app/chatgpt-auth";
import { defaultDecks, defaultWords, folders } from "@/lib/default-words";

export async function GET(){
 try{const db=getDb();for(const requiredDeckKey of ["toeic-lc-day2","toeic-rc-day2"]){const existingWords=await db.select({id:words.id}).from(words).where(eq(words.deckKey,requiredDeckKey)).limit(1);if(!existingWords.length){const deck=defaultDecks.find(item=>item.key===requiredDeckKey);if(deck)await db.insert(studyDecks).values(deck).onConflictDoNothing();const seed=defaultWords.filter(([deckKey])=>deckKey===requiredDeckKey).map(([deckKey,english,korean,note])=>({deckKey,english,korean,note}));for(let i=0;i<seed.length;i+=20)await db.insert(words).values(seed.slice(i,i+20)).onConflictDoNothing()}}const allDecks=await db.select().from(studyDecks).orderBy(asc(studyDecks.createdAt),asc(studyDecks.title));const user=await getChatGPTUser();const rows=user?await db.select({id:words.id,deckKey:words.deckKey,english:words.english,korean:words.korean,note:words.note,level:sql<number>`coalesce(${progress.level},0)`,wrongCount:sql<number>`coalesce(${progress.wrongCount},0)`,bookmarked:sql<number>`case when ${bookmarks.id} is null then 0 else 1 end`}).from(words).leftJoin(progress,sql`${progress.wordId}=${words.id} and ${progress.userId}=${user.userId}`).leftJoin(bookmarks,sql`${bookmarks.wordId}=${words.id} and ${bookmarks.userId}=${user.userId}`).orderBy(asc(words.id)):await db.select({id:words.id,deckKey:words.deckKey,english:words.english,korean:words.korean,note:words.note,level:sql<number>`0`,wrongCount:sql<number>`0`,bookmarked:sql<number>`0`}).from(words).orderBy(asc(words.id));const legacyHackers=new Set(["hackers-rc-day1","hackers-lc-day1"]);const decks=allDecks.filter(deck=>!legacyHackers.has(deck.key)||rows.some(word=>word.deckKey===deck.key));return new Response(JSON.stringify({folders,decks,words:rows.map(row=>({...row,bookmarked:Boolean(row.bookmarked)}))}),{headers:{"content-type":"application/json","cache-control":"no-store, max-age=0"}})}catch(e){return Response.json({error:e instanceof Error?e.message:"단어를 불러오지 못했어요."},{status:500})}
}
export async function POST(request:Request){const user=await getChatGPTUser();if(!user)return Response.json({error:"로그인이 필요해요."},{status:401});const b=await request.json() as {deckKey?:string;english?:string;korean?:string;note?:string;words?:{english?:string;korean?:string;note?:string}[]};const deckKey=b.deckKey?.trim();const incoming=b.words??[{english:b.english,korean:b.korean,note:b.note}];const valid=incoming.map(w=>({english:w.english?.trim().toLowerCase()??"",korean:w.korean?.trim()??"",note:w.note?.trim()??""})).filter(w=>w.english&&w.korean);if(!deckKey||!valid.length)return Response.json({error:"챕터, 영단어, 뜻을 모두 입력해줘."},{status:400});const db=getDb();for(const word of valid)await db.insert(words).values({deckKey,...word}).onConflictDoUpdate({target:[words.deckKey,words.english],set:{korean:word.korean,note:word.note}});return Response.json({ok:true,count:valid.length},{status:201})}
