export const folders=[{key:"ybm",title:"YBM 단어",description:"YBM 교재 단어 모음"},{key:"hackers",title:"해커스 단어",description:"해커스 교재 단어 모음"}];
export const defaultDecks=[{key:"toeic-rc-day1",title:"RC Day 1",folderKey:"ybm",kind:"RC"},{key:"toeic-rc-day2",title:"RC Day 2",folderKey:"ybm",kind:"RC"},{key:"toeic-lc-day1",title:"LC Day 1",folderKey:"ybm",kind:"LC"},{key:"toeic-lc-day2",title:"LC Day 2",folderKey:"ybm",kind:"LC"},{key:"hackers-day1",title:"Day 1",folderKey:"hackers",kind:"VOCAB"},{key:"hackers-day2",title:"Day 2",folderKey:"hackers",kind:"VOCAB"},{key:"hackers-day3",title:"Day 3",folderKey:"hackers",kind:"VOCAB"}];
export const defaultWords=[
  ["toeic-rc-day1","evaluate","평가하다","동사"],["toeic-rc-day1","appreciate","감사하다, 진가를 알아보다","동사"],["toeic-rc-day1","retirement","은퇴","명사"],["toeic-rc-day1","assistance","도움","명사"],["toeic-rc-day1","certificate","증명서, 자격증","명사"],["toeic-rc-day1","representative","대표자","명사·형용사"],["toeic-rc-day1","resident","주민","명사"],["toeic-rc-day1","exceed","초과하다","동사"],["toeic-rc-day1","earn","벌다, 얻다","동사"],["toeic-rc-day1","assembly line","조립 라인","명사"],["toeic-rc-day1","benefits package","복리 후생 제도","명사"],["toeic-rc-day1","expiration date","만기일","명사"],["toeic-rc-day1","warranty certificate","품질 보증서","명사"],["toeic-rc-day1","response","답장, 대응","명사"],["toeic-rc-day1","priority","우선, 우선권","명사"],["toeic-rc-day1","initiative","계획, 주도권","명사"],["toeic-rc-day1","maintenance","유지, 정비","명사"],["toeic-rc-day1","agreement","협약, 계약","명사"],["toeic-rc-day1","architect","건축가","명사"],["toeic-rc-day1","encourage","권장하다, 격려하다","동사"],
  ["toeic-rc-day1","shift","교대근무","명사"],["toeic-rc-day1","regularly","정기적으로","부사"],["toeic-rc-day1","reasonable","합리적인","형용사"],["toeic-rc-day1","concern","걱정, 관심사","명사"],["toeic-rc-day1","submission","제출","명사"],["toeic-rc-day1","assistant","보조원","명사"],["toeic-rc-day1","attendant","안내원, 수행원","명사"],["toeic-rc-day1","accountant","회계사","명사"],["toeic-rc-day1","based in ~","~에 본사를 둔","표현"],["toeic-rc-day1","banquet facility","연회 시설","명사"],["toeic-rc-day1","responsible for ~","~에 책임이 있는","표현"],["toeic-rc-day1","pavement","인도, 보도","명사"],["toeic-rc-day1","aim to + 동사원형","~하는 것을 목표로 하다","표현"],["toeic-rc-day1","branch","지점","명사"],["toeic-rc-day1","variation","변형, 변화","명사"],["toeic-rc-day1","purse","지갑","명사"],["toeic-rc-day1","brainstorming","아이디어 회의","명사"],["toeic-rc-day1","improvement","개선, 향상","명사"],["toeic-rc-day1","reservation","예약","명사"],["toeic-rc-day1","premier","최고의, 일류의","형용사"],["toeic-rc-day1","agency","대행사","명사"],["toeic-rc-day1","regional","지역의","형용사"],["toeic-rc-day1","agent","대리인","명사"],["toeic-rc-day1","fee","수수료","명사"],["toeic-rc-day1","recruitment","모집, 채용","명사"],["toeic-rc-day1","initial","처음의, 초기의","형용사"],["toeic-rc-day1","revise","수정하다","동사"],["toeic-rc-day1","appreciate","감사하다, 진가를 인정하다","동사"],["toeic-rc-day1","certificate","증명서, 증서, 자격증","명사"],["toeic-rc-day1","representative","대표자","명사·형용사"],["toeic-rc-day1","resident","주민, 거주자","명사"],["toeic-rc-day1","assembly line","조립 라인","명사"],["toeic-rc-day1","benefits package","복리후생 제도","명사"],["toeic-rc-day1","staff assembly","직원 총회","명사"],["toeic-rc-day1","expiration date","만기일, 유효기간","명사"],["toeic-rc-day1","warranty certificate","품질보증서","명사"],["toeic-rc-day1","panel","위원단, 배심원단","명사"],["toeic-rc-day1","assembly","조립, 집회, 회의","명사"],["toeic-rc-day1","convenience","편의, 편리","명사"],["toeic-rc-day1","associate","직원, 동료; 연상하다","명사·동사"],["toeic-rc-day1","publication","출판, 출판물","명사"],["toeic-rc-day1","critic","비평가, 평론가","명사"],["toeic-rc-day1","thought-provoking","시사하는 바가 많은","형용사"],["toeic-rc-day1","assemble","모으다, 조립하다","동사"],["toeic-rc-day1","host","주최하다","동사"],["toeic-rc-day1","a series of","일련의","표현"],["toeic-rc-day1","merger","합병","명사"],["toeic-rc-day1","advertisers","광고주들","명사"],["toeic-rc-day1","advertisement","광고","명사"],["toeic-rc-day1","suitable","적절한","형용사"],["toeic-rc-day1","exceptional","우수한, 이례적인","형용사"],["toeic-rc-day1","director of operations","운영 이사","명사"],["toeic-rc-day1","manufacturing","제조","명사"],["toeic-rc-day1","temporary","일시적인","형용사"],["toeic-rc-day1","detour","우회로","명사"],["toeic-rc-day1","inconvenience","불편함","명사"],["toeic-rc-day1","according to + 명사","명사에 따르면","표현"],["toeic-rc-day1","besides","게다가","부사"],["toeic-rc-day2","affordable","적당한, 가격이 알맞은","형용사"],["toeic-rc-day2","considerable","상당한","형용사"],["toeic-rc-day2","accessible","접근할 수 있는","형용사"],["toeic-rc-day2","significant","상당한, 중요한","형용사"],["toeic-rc-day2","relevant","관련 있는","형용사"],["toeic-rc-day2","informative","유익한","형용사"],["toeic-rc-day2","extensive","폭넓은","형용사"],["toeic-rc-day2","regional","지역의","형용사"],["toeic-rc-day2","operational","작동하는","형용사"],["toeic-rc-day2","complimentary","무료의","형용사"],["toeic-rc-day2","introductory","입문용의","형용사"],["toeic-rc-day2","supplementary","보충의","형용사"],["toeic-rc-day2","lengthy","너무 긴, 장황한","형용사"],["toeic-rc-day2","timely","시기적절한","형용사"],["toeic-rc-day2","confidential","기밀의","형용사"],["toeic-rc-day2","reliable","믿을 수 있는","형용사"],["toeic-rc-day2","responsible","책임이 있는","형용사"],["toeic-rc-day2","confident","확신하는","형용사"],["toeic-rc-day2","reliant on/upon","~에 의존하는","표현"],["toeic-rc-day2","impressed with","~에 감명받은","표현"],["toeic-rc-day2","informed about/of","~에 대해 통보받은","표현"],["toeic-rc-day2","responsive to","~에 대응하는","표현"],["toeic-rc-day2","relatively","비교적","부사"],["toeic-rc-day2","approximately","대략","부사"],["toeic-rc-day2","lately","최근","부사"],["toeic-rc-day2","shortly","곧","부사"],["toeic-rc-day2","nearly","거의, 대략","부사"],["toeic-rc-day2","closely","긴밀히, 면밀히","부사"],["toeic-rc-day2","knowledge","지식","명사"],["toeic-rc-day2","expansion","확장","명사"],["toeic-rc-day2","contribution","기부금, 투고, 기여","명사"],["toeic-rc-day2","reception","환영회, 접수처","명사"],["toeic-rc-day2","reputation","평판, 명성","명사"],["toeic-rc-day2","restriction","제한, 제약","명사"],["toeic-rc-day2","replacement","대체품, 후임자","명사"],["toeic-rc-day2","estimate","추정치, 견적서","명사"],["toeic-rc-day2","accurate","정확한","형용사"],["toeic-rc-day2","briefly","간략히","부사"],["toeic-rc-day2","valuable","소중한","형용사"],["toeic-rc-day2","eagerly","간절히","부사"],["toeic-rc-day2","consistently","지속적으로","부사"],["toeic-rc-day2","steadily","꾸준히","부사"],["toeic-rc-day2","properly","적절히","부사"],["toeic-rc-day2","renovations","보수 공사","명사"],["toeic-rc-day2","refer to","~을 참고하다","표현"],["toeic-rc-day2","rely on","~에 의지하다","표현"],["toeic-rc-day2","valid","유효한","형용사"],["toeic-rc-day2","equipment","장비","명사"],["toeic-rc-day2","anticipate","예상하다","동사"],["toeic-rc-day2","maximize","극대화하다","동사"],["toeic-rc-day2","operate","운영하다, 가동하다","동사"],["toeic-rc-day2","predict","예측하다","동사"],["toeic-rc-day2","organize","준비하다, 정리하다","동사"],["toeic-rc-day2","launch","출시하다","동사"],["toeic-rc-day2","indicate","나타내다","동사"],["toeic-rc-day2","assume","맡다, 추정하다","동사"],["toeic-rc-day2","emphasize","강조하다","동사"],["toeic-rc-day2","finalize","마무리 짓다","동사"],["toeic-rc-day2","specification","설명서","명사"],["toeic-rc-day2","specify","구체적으로 밝히다","동사"],["toeic-rc-day2","fasten","고정하다","동사"],["toeic-rc-day2","confused","혼란스러워하는","형용사"],["toeic-rc-day2","appropriate","해당하는, 적절한","형용사"],["toeic-rc-day2","cargo","화물","명사"],["toeic-rc-day2","entrepreneur","기업가","명사"],["toeic-rc-day2","aspect","측면, 양상","명사"],["toeic-rc-day2","shelving","선반","명사"],["toeic-rc-day2","efficiency","효율성","명사"],["toeic-rc-day2","storage","보관, 저장","명사"],["toeic-rc-day2","present","보여주다","동사"],["toeic-rc-day2","responsibility","책임","명사"],["toeic-rc-day2","determine","결정하다","동사"],["toeic-rc-day2","promote","촉진하다","동사"],["toeic-rc-day2","absence","부재","명사"],
  ["toeic-lc-day1","potted","화분에 심은","형용사"],
  ["toeic-lc-day1","examining a report","보고서를 검토하고 있는","표현"],
  ["toeic-lc-day1","paving a driveway","차도를 포장하고 있는","표현"],
  ["toeic-lc-day1","playing instruments","악기를 연주하고 있는","표현"],
  ["toeic-lc-day1","leaning / bending over","몸을 숙이고 있는","표현"],
  ["toeic-lc-day1","safety vest","안전조끼","명사"],
  ["toeic-lc-day1","briefcase","서류가방","명사"],
  ["toeic-lc-day1","grocery / groceries","식료품","명사"],
  ["toeic-lc-day1","a sheet of","한 장의","표현"],
  ["toeic-lc-day1","stack","더미, 무더기","명사"],
  ["toeic-lc-day1","unfold","펼치다","동사"],
  ["toeic-lc-day1","put on","착용하다","동사"],
  ["toeic-lc-day1","nail","못","명사"],
  ["toeic-lc-day1","hammer","망치로 치다","동사"],
  ["toeic-lc-day1","harbor","항구","명사"],
  ["toeic-lc-day1","pedestrian","보행자","명사"],
  ["toeic-lc-day1","unoccupied","비어 있는","형용사"],
  ["toeic-lc-day1","hallway","복도","명사"],
  ["toeic-lc-day1","be scattered","흩어져 있다","표현"],
  ["toeic-lc-day1","unattended","방치되어 있는","형용사"],
  ["toeic-lc-day1","be docked / tied in a harbor","항구에 정박되어 있다","표현"],
  ["toeic-lc-day1","fountain","분수대","명사"],
  ["toeic-lc-day1","be left open","열린 채로 있다","표현"],
  ["toeic-lc-day1","be leaning against","~에 기대어 있다","표현"],
  ["toeic-lc-day1","be raked into piles","갈퀴로 긁어모아 쌓여 있다","표현"],
  ["toeic-lc-day1","cartons","포장 상자","명사"],
  ["toeic-lc-day1","be lying / resting","놓여 있다","표현"],
  ["toeic-lc-day1","traffic light","신호등","명사"],
  ["toeic-lc-day1","flower pots","화분","명사"],
  ["toeic-lc-day1","polishing","닦고 있는","표현"],
  ["toeic-lc-day1","in a row","일렬로","표현"],
  ["toeic-lc-day1","railing","난간","명사"],
  ["toeic-lc-day1","bush","덤불","명사"],
  ["toeic-lc-day1","trim","다듬다, 잘라내다","동사"],
  ["toeic-lc-day1","aprons","앞치마","명사"],
  ["toeic-lc-day1","cash register","계산대","명사"],
  ["toeic-lc-day1","scatter","흩어 놓다, 흩뿌리다","동사"],
  ["toeic-lc-day2","luncheon","오찬","명사"],
  ["toeic-lc-day2","cater","음식을 공급하다","동사"],
  ["toeic-lc-day2","exhibit","전시회","명사"],
  ["toeic-lc-day2","revise","수정하다","동사"],
  ["toeic-lc-day2","lecture","강연","명사"],
  ["toeic-lc-day2","charter","전세 내다","동사"],
  ["toeic-lc-day2","banquet","연회","명사"],
  ["toeic-lc-day2","be sure to","반드시 ~하다","표현"],
  ["toeic-lc-day2","salmon","연어","명사"],
  ["toeic-lc-day2","keep track of","~을 파악하다, 추적하다","표현"],
  ["toeic-lc-day2","merchandise","상품","명사"],
  ["toeic-lc-day2","storage locker","보관함","명사"],
  ["toeic-lc-day2","warehouse","창고","명사"],
  ["toeic-lc-day2","lower level","아래층","명사"],
  ["toeic-lc-day2","wing","부속 건물","명사"],
  ["toeic-lc-day2","brochure","안내서","명사"],
  ["toeic-lc-day2","drawer","서랍","명사"],
  ["toeic-lc-day2","crate","나무 상자","명사"],
  ["toeic-lc-day2","vacuum cleaner","진공청소기","명사"],
  ["toeic-lc-day2","ship","배송하다","동사"],
  ["toeic-lc-day2","security","보안","명사"],
  ["toeic-lc-day2","activate","활성화하다","동사"],
  ["toeic-lc-day2","activities","활동","명사"],
  ["toeic-lc-day2","greet","맞이하다","동사"],
  ["toeic-lc-day2","greeting","인사, 인사말","명사"],
  ["toeic-lc-day2","clinic","진료소","명사"],
  ["toeic-lc-day2","patient","환자","명사"],
  ["toeic-lc-day2","organic","유기농의","형용사"],
  ["toeic-lc-day2","press release","보도자료","명사"],
  ["toeic-lc-day2","highway","고속도로","명사"],
  ["toeic-lc-day2","stop by","잠시 들리다","표현"],
  ["toeic-lc-day2","convenient","편리한","형용사"],
  ["hackers-day1","resume","이력서","명사"],
  ["hackers-day1","opening","공석, 개장","명사"],
  ["hackers-day1","applicant","지원자, 신청자","명사"],
  ["hackers-day1","requirement","필요조건","명사 · of/for"],
  ["hackers-day1","meet","만족시키다","동사"],
  ["hackers-day1","qualified","자격 있는, 적격의","형용사"],
  ["hackers-day1","candidate","지원자","명사"],
  ["hackers-day1","confidence","확신, 자신","명사"],
  ["hackers-day1","highly","매우, 대단히","부사"],
  ["hackers-day1","professional","전문적인, 직업의","형용사"],
  ["hackers-day1","interview","면접","명사"],
  ["hackers-day1","hire","고용하다","동사"],
  ["hackers-day1","training","교육, 훈련","명사"],
  ["hackers-day1","reference","추천서, 참고","명사"],
  ["hackers-day1","position","일자리, 직책, 두다","명사·동사"],
  ["hackers-day1","achievement","성취, 달성","명사"],
  ["hackers-day1","impressed","인상 깊게 생각하는","형용사"],
  ["hackers-day1","excellent","훌륭한","형용사"],
  ["hackers-day1","eligible","자격이 있는, 적격의","형용사"],
  ["hackers-day1","identify","알아보다, 확인하다","동사"],
  ["hackers-day1","associate","관련시키다","동사"],
  ["hackers-day1","condition","조건","명사"],
  ["hackers-day1","employment","고용","명사"],
  ["hackers-day1","lack","~이 없다, 부족","동사·명사"],
  ["hackers-day1","managerial","관리의","형용사"],
  ["hackers-day1","diligent","성실한","형용사"],
  ["hackers-day1","familiar","익숙한, 친숙한","형용사 · with"],
  ["hackers-day1","proficiency","숙달, 능숙","명사"],
  ["hackers-day1","prospective","장래의","형용사"],
  ["hackers-day1","appeal","관심을 끌다, 매력적이다","동사 · to"],
  ["hackers-day1","specialize","~을 전공하다","동사"],
  ["hackers-day1","apprehensive","걱정하는, 염려하는","형용사"],
  ["hackers-day1","consultant","고문","명사"],
  ["hackers-day1","entitle","자격을 주다","동사"],
  ["hackers-day1","degree","학위","명사"],
  ["hackers-day1","payroll","임금 대장","명사"],
  ["hackers-day1","recruit","모집하다","동사"],
  ["hackers-day1","certification","증명서","명사"],
  ["hackers-day1","occupation","직업","명사"],
  ["hackers-day1","wage","임금, 급료","명사"],
  ["hackers-day2","attire","복장","명사"],
  ["hackers-day2","code","규범, 암호","명사"],
  ["hackers-day2","concern","우려, 문제, 일; 영향을 미치다","명사·동사"],
  ["hackers-day2","policy","규정, 보험증권","명사"],
  ["hackers-day2","comply","준수하다, 따르다","동사"],
  ["hackers-day2","regulation","규정","명사"],
  ["hackers-day2","exception","예외","명사"],
  ["hackers-day2","adhere","지키다, 고수하다","동사 · to"],
  ["hackers-day2","severely","엄격하게, 심하게","부사"],
  ["hackers-day2","refrain","자제하다, 삼가다","동사 · from"],
  ["hackers-day2","permission","허락, 허가","명사"],
  ["hackers-day2","access","이용권한, 통로; 도달하다","명사·동사"],
  ["hackers-day2","thoroughly","철저하게, 완전히","부사"],
  ["hackers-day2","revise","수정하다, 변경하다","동사"],
  ["hackers-day2","approach","접근법, 처리방법; 다가오다","명사·동사"],
  ["hackers-day2","approval","승인, 인가","명사"],
  ["hackers-day2","form","종류, 유형","명사"],
  ["hackers-day2","immediately","즉시, 곧","부사"],
  ["hackers-day2","inspection","점검, 검사","명사"],
  ["hackers-day2","arrangement","준비, 마련, 주선","명사"],
  ["hackers-day2","procedure","절차","명사"],
  ["hackers-day2","negative","부정적인, 비판적인","형용사"],
  ["hackers-day2","mandate","명령하다; 권한, 지시","동사·명사"],
  ["hackers-day2","effect","효과, 영향; 결과적으로 ~을 가져오다","명사·동사"],
  ["hackers-day2","drastically","심하게, 과감하게, 철저하게","부사"],
  ["hackers-day2","according to","~에 따라","표현"],
  ["hackers-day2","enable","가능하게 하다","동사"],
  ["hackers-day2","standard","기준","명사"],
  ["hackers-day2","constant","지속적인","형용사"],
  ["hackers-day2","act","법령, 행동; 결정하다, 행동하다","명사·동사"],
  ["hackers-day2","compensation","보상금","명사"],
  ["hackers-day2","ban","금지","명사·동사"],
  ["hackers-day2","obligation","의무, 책임","명사"],
  ["hackers-day2","authorize","~을 인가하다, 권한을 부여하다","동사"],
  ["hackers-day2","prohibit","금지하다","동사"],
  ["hackers-day2","abolish","폐지하다","동사"],
  ["hackers-day2","enforce","시행하다, 집행하다","동사"],
  ["hackers-day2","habit","습관","명사"],
  ["hackers-day2","legislation","법률, 법규","명사"],
  ["hackers-day2","restrict","한정하다, 제한하다","동사"],
  ["hackers-day3","accustomed","익숙한","형용사"],
  ["hackers-day3","corporation","주식회사, 법인","명사"],
  ["hackers-day3","demanding","요구가 많은, 힘든","형용사"],
  ["hackers-day3","colleague","동료","명사"],
  ["hackers-day3","division","부서","명사"],
  ["hackers-day3","request","요청","명사·동사"],
  ["hackers-day3","efficiently","효율적으로","부사"],
  ["hackers-day3","manage","~을 경영하다","동사"],
  ["hackers-day3","submit","제출하다","동사"],
  ["hackers-day3","directly","곧바로","부사"],
  ["hackers-day3","remind","~에게 상기시키다","동사"],
  ["hackers-day3","instruct","지시하다, 가르치다","동사"],
  ["hackers-day3","deadline","마감일","명사"],
  ["hackers-day3","sample","견본; 시식하다","명사·동사"],
  ["hackers-day3","notify","알리다","동사"],
  ["hackers-day3","perform","행하다, 실행하다","동사"],
  ["hackers-day3","monitor","감독하다","동사"],
  ["hackers-day3","deserve","~할 만하다","동사"],
  ["hackers-day3","assignment","일, 임무, 과제","명사"],
  ["hackers-day3","entire","전체의","형용사"],
  ["hackers-day3","release","발표하다, 공개하다","동사"],
  ["hackers-day3","extension","연장, 연기; 전화 내선","명사"],
  ["hackers-day3","electronically","컴퓨터로, 전자적으로","부사"],
  ["hackers-day3","attendance","출근, 출석","명사"],
  ["hackers-day3","absolutely","절대적으로, 완전히","부사"],
  ["hackers-day3","delegate","위임하다; 대표","동사·명사"],
  ["hackers-day3","attentively","주의 깊게, 조심스럽게","부사"],
  ["hackers-day3","supervision","감독","명사"],
  ["hackers-day3","workshop","연수","명사"],
  ["hackers-day3","draw","끌다","동사"],
  ["hackers-day3","revision","수정, 개정","명사"],
  ["hackers-day3","reluctantly","마지못해, 꺼려하며","부사"],
  ["hackers-day3","acquaint","~에게 숙지시키다, 잘 알게 하다","동사"],
  ["hackers-day3","convey","전달하다","동사"],
  ["hackers-day3","check","검사하다","동사"],
  ["hackers-day3","headquarters","본부","명사"],
  ["hackers-day3","file","정리하다, 제출하다","동사"],
  ["hackers-day3","oversee","감독하다","동사"],
  ["hackers-day3","involved","관여하는, 관계된","형용사"],
  ["hackers-day3","concentrate","집중하다","동사"],
] as const;
