export const folders=[{key:"ybm",title:"YBM 단어",description:"YBM 교재 단어 모음"},{key:"hackers",title:"해커스 단어",description:"해커스 교재 단어 모음"}];
export const defaultDecks=[{key:"toeic-rc-day1",title:"RC Day 1",folderKey:"ybm",kind:"RC"},{key:"toeic-lc-day1",title:"LC Day 1",folderKey:"ybm",kind:"LC"},{key:"hackers-rc-day1",title:"RC Day 1",folderKey:"hackers",kind:"RC"},{key:"hackers-lc-day1",title:"LC Day 1",folderKey:"hackers",kind:"LC"}];
export const defaultWords=[
  ["toeic-rc-day1","evaluate","평가하다","동사"],["toeic-rc-day1","appreciate","감사하다, 진가를 알아보다","동사"],["toeic-rc-day1","retirement","은퇴","명사"],["toeic-rc-day1","assistance","도움","명사"],["toeic-rc-day1","certificate","증명서, 자격증","명사"],["toeic-rc-day1","representative","대표자","명사·형용사"],["toeic-rc-day1","resident","주민","명사"],["toeic-rc-day1","exceed","초과하다","동사"],["toeic-rc-day1","earn","벌다, 얻다","동사"],["toeic-rc-day1","assembly line","조립 라인","명사"],["toeic-rc-day1","benefits package","복리 후생 제도","명사"],["toeic-rc-day1","expiration date","만기일","명사"],["toeic-rc-day1","warranty certificate","품질 보증서","명사"],["toeic-rc-day1","response","답장, 대응","명사"],["toeic-rc-day1","priority","우선, 우선권","명사"],["toeic-rc-day1","initiative","계획, 주도권","명사"],["toeic-rc-day1","maintenance","유지, 정비","명사"],["toeic-rc-day1","agreement","협약, 계약","명사"],["toeic-rc-day1","architect","건축가","명사"],["toeic-rc-day1","encourage","권장하다, 격려하다","동사"],
  ["toeic-lc-day1","potted","화분에 심은","형용사"],
  ["toeic-lc-day1","examining a report","보고서를 검토하고 있는","표현"],
  ["toeic-lc-day1","paving a driveway","차도를 포장하고 있는","표현"],
  ["toeic-lc-day1","playing instruments","악기를 연주하고 있는","표현"],
  ["toeic-lc-day1","leaning / bending over","몸을 숙이고 있는","표현"],
  ["toeic-lc-day1","safety vest","안전조끼","명사"],
  ["toeic-lc-day1","briefcase","서류가방","명사"],
  ["toeic-lc-day1","grocery / groceries","식료품","명사"],
  ["toeic-lc-day1","a sheet of","한 장의","표현"],
  ["toeic-lc-day1","stack","더미, 무더기","명사"],
  ["toeic-lc-day1","unfold","펼치다","동사"],
  ["toeic-lc-day1","put on","착용하다","동사"],
  ["toeic-lc-day1","nail","못","명사"],
  ["toeic-lc-day1","hammer","망치로 치다","동사"],
  ["toeic-lc-day1","harbor","항구","명사"],
  ["toeic-lc-day1","pedestrian","보행자","명사"],
  ["toeic-lc-day1","unoccupied","비어 있는","형용사"],
  ["toeic-lc-day1","hallway","복도","명사"],
  ["toeic-lc-day1","be scattered","흩어져 있다","표현"],
  ["toeic-lc-day1","unattended","방치되어 있는","형용사"],
  ["toeic-lc-day1","be docked / tied in a harbor","항구에 정박되어 있다","표현"],
  ["toeic-lc-day1","fountain","분수대","명사"],
  ["toeic-lc-day1","be left open","열린 채로 있다","표현"],
  ["toeic-lc-day1","be leaning against","~에 기대어 있다","표현"],
  ["toeic-lc-day1","be raked into piles","갈퀴로 긁어모아 쌓여 있다","표현"],
  ["toeic-lc-day1","cartons","포장 상자","명사"],
  ["toeic-lc-day1","be lying / resting","놓여 있다","표현"],
  ["toeic-lc-day1","traffic light","신호등","명사"],
  ["toeic-lc-day1","flower pots","화분","명사"],
  ["toeic-lc-day1","polishing","닦고 있는","표현"],
  ["toeic-lc-day1","in a row","일렬로","표현"],
  ["toeic-lc-day1","railing","난간","명사"],
  ["toeic-lc-day1","bush","덤불","명사"],
  ["toeic-lc-day1","trim","다듬다, 잘라내다","동사"],
  ["toeic-lc-day1","aprons","앞치마","명사"],
  ["toeic-lc-day1","cash register","계산대","명사"],
  ["toeic-lc-day1","scatter","흩어 놓다, 흩뿌리다","동사"],
] as const;
